---
# Sensor button
#    uid:
#    page_id:
#    row:
#    column:
#    row_span:
#    column_span:
#    text:
#    icon:
#    icon_color:
#    sensor_id:
#    sensor_font:

# This section adds a button to LVGL page main_page
lvgl:
  pages:
    - id: !extend ${page_id | default("main_page")}
      widgets:
        - container:
            id: ${uid}
            grid_cell_row_pos: ${row}
            grid_cell_column_pos: ${column}
            grid_cell_row_span: ${row_span | default(1)}
            grid_cell_column_span: ${column_span | default(2)}
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            # outline_width: 1
            # outline_color: red
            widgets:
              - button:
                  id: button_${sensor_id}
                  width: 100%
                  height: 100%
                  layout:
                    type: grid
                    grid_columns: [content, fr(1)]
                    grid_rows: [fr(1), fr(1)]
                  widgets:
                    - label:
                        id: icon_${sensor_id}
                        text_font: $icon_font
                        text_color: ${icon_color | default("$label_on_color")}
                        grid_cell_row_pos: 0
                        grid_cell_column_pos: 0
                        grid_cell_row_span: 2
                        grid_cell_x_align: start
                        grid_cell_y_align: center
                        text: ${icon}
                    - label:
                        id: label_${sensor_id}
                        text_font: $text_font
                        width: 100%
                        long_mode: wrap
                        grid_cell_row_pos: 0
                        grid_cell_column_pos: 1
                        grid_cell_x_align: stretch
                        grid_cell_y_align: start
                        text_align: left
                        text: ${text}
                    - label:
                        id: data_${sensor_id}
                        text_font: ${sensor_font | default("$text_font")}
                        grid_cell_row_pos: 1
                        grid_cell_column_pos: 1
                        grid_cell_x_align: start
                        grid_cell_y_align: end
                        text_align: left
                        text: '----'


# Update button when sensor value changes
sensor:
  - id: !extend ${sensor_id}
    on_value:
      then:
        - lvgl.label.update:
            id: data_${sensor_id}
            text:
              format: "%.1f %s"
              args: ['x', 'id(${sensor_id}).get_unit_of_measurement_ref().c_str()']
