---
# Hardware configuration file
# Guition ESP32-P4-jc4880p443 4.3" 480X800
#

substitutions:
  # Screen Size (Configured as Lanscape)
  screen_height: 480
  screen_width: 800

esphome:
  min_version: 2026.1.0
  project:
    name: "Guition.ESP32-P4-jc4880p443"
    version: "1.0"

esp32:
  board: esp32-p4-evboard
  flash_size: 16Mb
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: y

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

# -------------------------------------------
# Internal outputs
# -------------------------------------------
output:
  # Backlight LED
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight_pwm
    frequency: 100Hz
    inverted: false

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    entity_category: config
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Speaker Amplifier Enable
# -------------------------------------------
switch:
  - platform: gpio
    id: my_amp
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO11
    restore_mode: RESTORE_DEFAULT_ON

# -------------------------------------------
# i2c bus
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

# -------------------------------------------
# Touchscreen
# -------------------------------------------
touchscreen:
  - platform: gt911
    i2c_id: bus_a
    id: my_touchscreen
    display: device_display
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: device_display
    model: JC4880P443
    update_interval: never
    auto_clear_enabled: false
    rotation: 90
    dimensions:
      width: 480
      height: 800

# Special LVGL settings required for this display
lvgl:
  byte_order: little_endian

# -------------------------------------------
# Audio - speaker/mic
# -------------------------------------------
i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

audio_dac:
  - platform: es8311
    id: my_dac
    i2c_id: bus_a
    address: 0x18

audio_adc:
  - platform: es7210
    id: my_adc
    i2c_id: bus_a
    address: 0x36

microphone:
  - platform: i2s_audio
    id: my_microphone
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO48
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: my_speaker
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO9
    audio_dac: my_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

  - platform: mixer
    id: mixing_speaker
    output_speaker: my_speaker
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
