# Guition-ESP32-P4-JC1060P470 7" Capacitive touch
#
# Hardware configuration file
---

substitutions:
  # Screen Size
  screen_height: 1200
  screen_width: 800

esphome:
  min_version: 2026.1.0
  project:
    name: "Guition.ESP32-P4-JC1060P470"
    version: "1.0"

esp32:
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

esp_ldo:
  - channel: 3
    id: dsi_phy_enable
    voltage: 2.5V
    adjustable: true
  - channel: 4
    id: sd_card_power
    voltage: 2.7V
    adjustable: true

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

# -------------------------------------------
# Network hardware
# -------------------------------------------

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

# -------------------------------------------
# Internal outputs
# -------------------------------------------
output:
  - id: gpio_backlight_pwm
    platform: ledc
    pin: GPIO23

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

# -------------------------------------------
# i2c bus
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

# -------------------------------------------
# Touchscreen
# -------------------------------------------
touchscreen:
  - platform: gt911
    id: my_touchscreen
    # reset_pin: GPIO23  # Shared with backlight
    interrupt_pin: GPIO21
#   on_touch:
#     - logger.log:
#           format: Touch at (%d, %d)
#           args: [touch.x, touch.y]
#     - lambda: |-
#           ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
#               touch.x,
#               touch.y,
#               touch.x_raw,
#               touch.y_raw
#               );

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    model: JC1060P470
    id: my_display
    update_interval: 17ms
    reset_pin:
      number: GPIO05
    hsync_pulse_width: 20

# Special LVGL settings required for this display
lvgl:
  byte_order: little_endian

# -------------------------------------------
# Audio - speaker/mic
# -------------------------------------------
i2s_audio:
  - id: audio_bus
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: bus_a
    address: 0x18

audio_adc:
  - platform: es7210
    id: es7210_adc
    i2c_id: bus_a
    address: 0x36

microphone:
  - platform: i2s_audio
    id: my_microphone
    i2s_audio_id: audio_bus
    i2s_din_pin: GPIO48
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    id: my_speaker
    i2s_audio_id: audio_bus
    i2s_dout_pin: GPIO9
    audio_dac: es8311_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

  - platform: mixer
    id: mixing_speaker
    output_speaker: my_speaker
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

switch:
  - platform: gpio
    id: audio_amplifier
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO11
    restore_mode: RESTORE_DEFAULT_ON
