---
# Hardware configuration file
# Guition-ESP32-P4-JC8012P4A1 10.1"  1280 x 800 Smart Screen
#
# http://pan.jczn1688.com/directlink/1/HMI%20display/JC8012P4A1C_I_W_Y.zip
#

external_components:
  - source: github://willumpie82/esphome@dev
    components: [mipi_dsi]
  - source: github://kvj/esphome@jd9365_gsl3680
    components: [gsl3680]

substitutions:
  # Screen Size
  screen_height: 1280
  screen_width: 800

esphome:
  min_version: 2026.1.0
  project:
    name: "Guition.ESP32-P4-JC8012P4A1"
    version: "1.0"

esp32:
  variant: esp32p4
  flash_size: 16MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

# Special LVGL settings required for this display
lvgl:
  byte_order: little_endian

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

# -------------------------------------------
# Network hardware
# -------------------------------------------
esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

# -------------------------------------------
# Internal outputs
# -------------------------------------------
output:
  # Backlight LED
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight_pwm
    frequency: 100Hz
    min_power: 0.03
    zero_means_zero: true

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON

# -------------------------------------------
# i2c bus
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

i2c_device:
  - id: i2cdev1
    address: 0x18
  - id: i2cdev2
    address: 0x32
  - id: i2cdev3
    address: 0x36
  - id: i2cdev4
    address: 0x40

# -------------------------------------------
# Touchscreen
# -------------------------------------------
touchscreen:
  - platform: gsl3680
    id: my_touchscreen
    reset_pin: GPIO22
    interrupt_pin: GPIO21
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: true

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    model: JC8012P4A1
    id: my_display
    update_interval: never
    reset_pin: GPIO27
    rotation: 180
    auto_clear_enabled: false
    color_order: RGB
    dimensions:
      width: 800
      height: 1280

# -------------------------------------------
# Audio - speaker/mic
# -------------------------------------------
i2s_audio:
  - id: i2s_output
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12
    i2s_mclk_pin: GPIO13

audio_dac:
  - platform: es8311
    id: es8311_dac
    bits_per_sample: 16bit
    sample_rate: 16000
    use_microphone: true

microphone:
  - platform: i2s_audio
    id: my_microphone
    i2s_din_pin: GPIO11
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external

speaker:
  - platform: i2s_audio
    i2s_audio_id: i2s_output
    id: my_speaker
    i2s_dout_pin: GPIO9
    dac_type: external
    sample_rate: 16000
    bits_per_sample: 16bit
    channel: stereo
    audio_dac: es8311_dac
  - platform: mixer
    id: mixing_speaker
    output_speaker: my_speaker
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never
  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
