---
# The Waveshare ESP32-P4-WIFI6-Touch-LCD-7B is a self contained, 7 inch 1024x600 touchscreen display with an ESP32-P4 MCU.
# It has an ESP32-C6 co-processor that gives the P4 Wi-Fi capabilities.
#
# Schematic: https://files.waveshare.com/wiki/ESP32-P4-WIFI6-Touch-LCD-7B/ESP32-P4-WIFI6-Touch-LCD-7B.pdf

substitutions:
  # Screen Size
  screen_height: 600
  screen_width: 1024

esphome:
  min_version: 2026.2.0
  project:
    name: "Waveshare.ESP32-P4-WIFI6-Touch-LCD-7B"
    version: "1.0"

esp32:
  variant: esp32p4
  flash_size: 32MB
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: true

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

psram:
  mode: hex
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp_ldo:
  - voltage: 2.5V
    channel: 3

# -------------------------------------------
# Touchscreen gt911 i2c
# -------------------------------------------
i2c:
  - id: bus_a
    sda: GPIO07
    scl: GPIO08
    frequency: 400kHz
    scan: true

touchscreen:
  - platform: gt911
    id: my_touchscreen
    i2c_id: bus_a
    reset_pin: GPIO23
    update_interval: 50ms
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: false
      # on_touch:
      #   - logger.log:
      #   format: Touch at (%d, %d)
      #   args: [touch.x, touch.y]
      #   - lambda: |-
      #       ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
      #       touch.x,
      #       touch.y,
      #       touch.x_raw,
      #       touch.y_raw
      #       );

# -------------------------------------------
# Backlight
# -------------------------------------------
output:
  - platform: ledc
    id: gpio_backlight_pwm
    pin: GPIO32
    inverted: true
    frequency: 1000Hz

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

# -------------------------------------------
# Display
# -------------------------------------------
display:
  - platform: mipi_dsi
    id: main_display
    model: WAVESHARE-ESP32-P4-WIFI6-TOUCH-LCD-7B
    reset_pin:
      number: 33
    rotation: 180
    update_interval: never
    auto_clear_enabled: false
    dimensions:
      width: 1024
      height: 600

# Special LVGL settings required for this display
lvgl:
  byte_order: little_endian

# -------------------------------------------
# Audio devices
# -------------------------------------------

# ===== Amplifier Control =====
switch:
  - platform: gpio
    id: audio_amplifier
    name: Speaker Enable
    icon: "mdi:speaker"
    entity_category: config
    pin: GPIO53  # BSP_POWER_AMP_IO
    restore_mode: RESTORE_DEFAULT_ON

# ===== ES8311 Audio Codec Configuration =====
i2s_audio:
  - id: audio_bus
    i2s_mclk_pin: GPIO13
    i2s_lrclk_pin: GPIO10
    i2s_bclk_pin: GPIO12

audio_dac:
  - platform: es8311
    id: es8311_dac
    i2c_id: bus_a
    address: 0x18

audio_adc:
  - platform: es7210
    id: es7210_adc
    i2c_id: bus_a
    address: 0x40

# ===== Microphone =====
microphone:
  - platform: i2s_audio
    id: my_microphone
    i2s_audio_id: audio_bus
    i2s_din_pin: GPIO11
    sample_rate: 16000
    bits_per_sample: 16bit
    adc_type: external
    # on_data:
    #   - logger.log:
    #       format: "Microphone data received: %d bytes"
    #       args: [x.size()]

# ===== Speaker & Audio Pipeline =====
speaker:
  - platform: i2s_audio
    id: my_speaker
    i2s_audio_id: audio_bus
    i2s_dout_pin: GPIO9
    audio_dac: es8311_dac
    dac_type: external
    channel: mono
    buffer_duration: 100ms
    bits_per_sample: 16bit
    sample_rate: 48000

  - platform: mixer
    id: mixing_speaker
    output_speaker: my_speaker
    source_speakers:
      - id: announcement_mixing_input
        timeout: never
      - id: media_mixing_input
        timeout: never

  - platform: resampler
    id: announcement_resampling_speaker
    output_speaker: announcement_mixing_input
    sample_rate: 48000
    bits_per_sample: 16

  - platform: resampler
    id: media_resampling_speaker
    output_speaker: media_mixing_input
    sample_rate: 48000
    bits_per_sample: 16
