# Substitution variables used through the codebase
---

external_components:
  - source: github://pr#13987
    components: [lvgl]
    refresh: 1h


substitutions:
  # Envoy serial number
  envoy_id: '122030047695'
  # envoy_id: !secret envoy_id
  enpower_id: !secret enpower_id

  icon_font: mdi_icons_40
  text_font: nunito_18
  sensor_font: nunito_36
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"

  # LCD back light modes - Code in backlight_time.yaml
  # Set Day mode - starts at Sunrise - screen at 100%
  touchscreen_daytime_brightness: "100%"
  # Set Evening mode -  starts at Sunset - screen at 50% (may need to be brighter for some screens)
  touchscreen_nighttime_brightness: "50%"
  # Set Night mode start time (default is midnight)
  touchscreen_night_hour: "0"      # Hour for night mode (0-23)
  touchscreen_night_minute: "0"    # Minute for night mode (0-59)
  # Set touchscreen idle timeout - In night mode back light goes off after this amount of time
  touchscreen_idle_timeout: "60s"

  # Screen Size
  screen_height: '480'
  screen_width: '960'

esphome:
  name: sdl-480px-test
  friendly_name: SDL 480px-test
  on_boot:
    - priority: 400
      then:
        - script.execute: update_loading_page


logger:
  level: debug

# Time update script - This is run once per second. Use it to update any time related labels.
script:
  - id: time_update
    then:
      # The format %I:%M %p will display the time in a 12-hour format with "am" or "pm" included
      - lvgl.label.update:
          id: time_label
          text: !lambda 'return id(system_time).now().strftime("%l:%M %P");'

packages:
  # Generic configuration for ESP32 screens
  # All the colors
  colors: !include esphome-modular-lvgl-buttons/common/color.yaml
  # Fonts you need
  fonts: !include esphome-modular-lvgl-buttons/common/fonts.yaml
  # 1000s of glyphs
  glyphs: !include esphome-modular-lvgl-buttons/common/mdi_glyph_substitutions.yaml
  # Some basic sensors
  sensors: !include esphome-modular-lvgl-buttons/sensors/sensors_base-SDL.yaml
  # Get the time from HA
  time: !include esphome-modular-lvgl-buttons/common/time_homeassistant.yaml
  # Styles + Themes
  theme_style: !include esphome-modular-lvgl-buttons/common/theme_style.yaml
  # theme_style: !include esphome-modular-lvgl-buttons/common/theme_style_debug.yaml

  # Harware description file
  hardware: !include esphome-modular-lvgl-buttons/hardware/SDL-lvgl.yaml

  # Basic boot screen with ESPHome logo and device diagnostic info
  loading_screen: !include esphome-modular-lvgl-buttons/pages/loading_480px.yaml
  # info screen - WiFi login, IP address, MAC address etc
  info_screen: !include esphome-modular-lvgl-buttons/pages/info.yaml

  solar: !include esphome-modular-lvgl-buttons/solar/update_solar.yaml
  realtime_solar: !include esphome-modular-lvgl-buttons/solar/sensors_assets_solar_realtime.yaml

  # This section will add buttons and page to your screen using the ESPHome package system.
  # Each package has all the code required for the button or page (LVGL, sensors, etc)


  # Add a button that displays the time
  button_1: !include
    file: esphome-modular-lvgl-buttons/buttons/sensor_button.yaml
    vars:
      uid: button_1
      row: 0
      column: 0
      text: Energy Consumption today
      icon: $mdi_meter_electric_outline
      icon_color: red
      sensor_id: sensor_energy_consumption_today
      sensor_font: nunito_24

  button_3: !include
    file: esphome-modular-lvgl-buttons/buttons/sensor_button.yaml
    vars:
      uid: button_3
      row: 1
      column: 0
      text: Net Consumption today
      icon: $mdi_transmission_tower_import
      icon_color: deep_orange
      sensor_id: sensor_net_energy_consumption_today
      sensor_font: nunito_24

  button_4: !include
    file: esphome-modular-lvgl-buttons/buttons/sensor_button.yaml
    vars:
      uid: button_4
      row: 2
      column: 0
      text: Production today
      icon: $mdi_solar_power
      icon_color: green
      sensor_id: sensor_energy_production_today
      sensor_font: nunito_24

  button_5: !include
    file: esphome-modular-lvgl-buttons/buttons/sensor_button.yaml
    vars:
      uid: button_5
      row: 3
      column: 0
      text: Net Production today
      icon: $mdi_transmission_tower_export
      icon_color: light_green
      sensor_id: sensor_net_energy_production_today
      sensor_font: nunito_24

  # Add a button that displays the time
  button_2: !include
    file: esphome-modular-lvgl-buttons/buttons/time_button.yaml
    vars:
      uid: button_2
      row: 0
      column: 3
      text: 00:00
      click_page: info_screen


# This is the main LVGL section. We start with a simple grid.
lvgl:
  pages:
    - id: main_page
      layout: 4x8
      styles: page_style
      <<: !include esphome-modular-lvgl-buttons/widgets/swipe_navigation.yaml
      widgets:
        # You can use the package section above to add prebuilt button types or build your own custom button from scratch here.
        - container:
            id: consumption_chart
            grid_cell_x_align: stretch
            grid_cell_y_align: stretch
            grid_cell_row_pos: 1
            grid_cell_column_pos: 3
            grid_cell_row_span: 2
            grid_cell_column_span: 3
            pad_left: 40
            pad_bottom: 25
            pad_right: 5
            pad_top: 5
            widgets:
              - chart:
                  id: consumption_chart_widget
                  width: 100%
                  height: 100%
                  bg_opa: TRANSP
                  border_width: 0
                  indicator:
                    opa: TRANSP
                  type: LINE
                  point_count: 288
                  div_line_count: [4, 5]
                  y_axis:
                    min_value: 0
                    max_value: 15000
                  series:
                    - id: consumption_chart_series
                      color: 0xF37320
                      y_axis: PRIMARY_Y

# If you want to use other icons add them to the list here
font:
  # http://materialdesignicons.com/cdn/7.4.47/
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: mdi_icons_40
    size: 40
    bpp: 8
    glyphs: [
      $mdi_bed,  # mdi-bed - bedroom icon
      $mdi_brightness_6,  # mdi-brightness-6 - brightness slider icon
      $mdi_bulkhead_light,  # mdi-bulkhead-light - bulkhead fixture
      $mdi_ceiling_fan_light,  # mdi-ceiling-fan-light - ceiling fan with light
      $mdi_ceiling_light,  # mdi-ceiling-light - ceiling fixture
      $mdi_chevron_down,  # mdi-chevron-down - close/collapse button
      $mdi_chevron_up,  # mdi-chevron-up - back/expand button
      $mdi_circle_opacity,  # mdi-circle-opacity - saturation slider icon
      $mdi_coach_lamp,  # mdi-coach-lamp - outdoor coach light
      $mdi_eyedropper,  # mdi-eyedropper - spectrum mode toggle
      $mdi_floor_lamp,  # mdi-floor-lamp - floor lamp
      $mdi_grid,  # mdi-grid - grid mode toggle
      $mdi_home,  # mdi-home - home/back navigation
      $mdi_information_box,  # mdi-information-box - info screen
      $mdi_lamp,  # mdi-lamp - table lamp
      $mdi_led_strip,  # mdi-led-strip - LED strip light
      $mdi_lightbulb,  # mdi-lightbulb - generic bulb icon
      $mdi_string_lights,  # mdi-string-lights - decorative string lights
      $mdi_track_light,  # mdi-track-light - track lighting
      $mdi_white_balance_sunny,  # mdi-white-balance-sunny - color temp/sun icon
      $mdi_solar_power,  # mdi-solar-power - solar production
      $mdi_meter_electric_outline,  # mdi-meter-electric-outline - energy consumption
      $mdi_transmission_tower_import,  # mdi-transmission-tower-import - grid import (net consumption)
      $mdi_transmission_tower_export,  # mdi-transmission-tower-export - grid export (net production)
    ]
